version: '3.8'

services:
  employeemanager_db:
    image: mysql:8.0
    container_name: employeemanager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourrootpassword # Root user password
      MYSQL_DATABASE: employee_manager     # Database name
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  employeemanager_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employeemanager_app
    ports:
      - "8080:8080"
    depends_on:
      - employeemanager_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://employeemanager_db:3306/employee_manager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yourrootpassword
    # This command ensures that the application starts only after the tests are run
    command: ["sh", "-c", "mvn test && java -jar employeemanager-app.jar"]

volumes:
  db_data:
